### ISSUE TITLE
SignUp Wizard: CardWizard error

### ISSUE THREAD

**Issue by marcierempel** [secc/RockPlugins#25]
Why does the card wizard block show up as blank sometimes when it's in card wizard mode. It was working, now it's not.
![capture](https://user-images.githubusercontent.com/44587882/48514214-13dfdf80-e81b-11e8-92e4-c5b34539cbac.JPG)

**Comment by marcierempel** [comment]
Also, when I go in to the sign up form after choosing a date and time, the serving role is the same - it's always picking what is set as the default and not what the person selected.

**Comment by marcierempel** [comment]
I was able to figure out the correct URL. For some reason it was dropping the ?show=signup after the page number.

**Comment by yichiu1231** [comment]
Hi, I have same issue like you mention "Also, when I go in to the sign up form after choosing a date and time, the serving role is the same - it's always picking what is set as the default and not what the person selected." 

How did you fix that?

Thank you.

**Comment by yichiu1231** [comment]
> Also, when I go in to the sign up form after choosing a date and time, the serving role is the same - it's always picking what is set as the default and not what the person selected.

Hi, I have some issue, can you tell me how did you fix this? Thank you.

**Comment by cbump** [comment]
These issues are fixed in v1.2 of the plugin which is currently in review.  I expect that it'll be ready to install either later tonight or sometime tomorrow.  Sorry about the inconvenience.  Thanks!
