### ISSUE TITLE
CardWizard: Role description not coming through

### ISSUE THREAD

**Issue by marcierempel** [secc/RockPlugins#26]
When using the CardWizard template, the role description is going back to the default on the form and the Connection. I tested in the Genius and CardPage templates and they both seem to be working properly. I just installed November 14 so I should have the most recent version of the plugin. Can someone tell me if I'm doing something wrong or if there's a bug in the template. I'm trying to get this operational by this weekend.

**Comment by cbump** [comment]
Hey Marcie - I started a Direct Message with you in Slack.  I'll work with you there to try to get to the bottom of this.  Thanks!

**Comment by cbump** [comment]
This should be resolved now.  Closing the issue.
