### ISSUE TITLE
Sign-Up Wizard: Partitions Are Sorted By Last Added

### ISSUE THREAD

**Issue by arranf** [secc/RockPlugins#30]
The list of partitions is generally sorted on a first come/first served basis - if you add a new role/defined type to the partitions after the block settings are initially saved then they will appear in that order.

I've solved this by altering the the last line of `GetTree` to be `return partitionList.OrderBy(a => a["Entity"].ToString()).ToList();` but I've not tested this in conjunction with your recent change to schedule ordering in ab4905aec6f8312e9d38dc8367495735021911c7 to fix #21 so I'm unsure of what interaction may exist there (hence the lack of PR).

**Comment by cbump** [comment]
I'm going to change this line to look at the Entity to see if it has an order and prefer that to the ToString() value:

`partitionList = partitionList.OrderBy( a => a["Entity"].GetType().GetProperty( "Order" ) != null ? a["Entity"].GetType().GetProperty( "Order" ).GetValue( a["Entity"], null ) : 0 ).ThenBy( a => a["Entity"].ToString() ).ToList();`

Thoughts?

**Comment by arranf** [comment]
Sounds good to me!

**Comment by cbump** [comment]
This was released in the Rock Shop over the weekend.  Thanks for all your help with this Arran!
