### ISSUE TITLE
Pastoral Plugin - Delete Test Post

### ISSUE THREAD

**Issue by craigmash** [secc/RockPlugins#36]
Is there a way to delete a test hospitalization that I did?

**Comment by craigmash** [comment]
Was able to delete it in the Manage Workflows screen.

**Comment by cbump** [comment]
The easiest way to do this is to follow these steps:

1. Go into General Settings within Rock.
2. Go to "Workflow Configuration"
3. Expand the "Pastoral Care" category
4. Select "Hospital Admission" workflow
5. Select the "Manage Workflows" button (the one that looks like a list)
6. Find the workflow you want to delete and click the "X" button and confirm you want to delete it.
