### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by craigmash** [secc/RockPlugins#38]
I have found some email notification options in the workflow, but turning them on does not seem to be sending any emails. Anyone able to help me get this working? Just need emails sent when someone is added, visited or discharged.

**Comment by craigmash** [comment]
I noticed in the log it said...

Homebound  Resident Setup Info Activity  > Form Entry Action : Could not send  form notification due to no assigned person or group

Homebound Resident Summary Activity (109) > Entry Form Action (388): Could not send form notification due to no assigned person or group

I did have myself assigned. If I move the  Set Assignee action above the Form Entry, an email gets sent. However, it sends it well before the information is saved. Would not want it to send until after the form is submitted.

**Comment by cbump** [comment]
What if you add a workflow action to just send an email in the places you want it to be sent?  You wouldn't have to assign the task and you could send it to a distribution group.  It's a little bit of work to customize the workflow/plugin but you could probably get to the point where it functions exactly like you want/need.

**Comment by craigmash** [comment]
That is kinda what I was thinking. I am just so new at this, not sure how to get an email that includes information from the form (like the persons name and if it is an added, visit or discharge) and also the View Details button.

**Comment by craigmash** [comment]
Is there a way to separately activate the Workflow Form Notification?
