### ISSUE TITLE
Signup Wiizard: Role Totals

### ISSUE THREAD

**Issue by TheArkChurch** [secc/RockPlugins#41]
We're having an Issue where the totals aren't being reduced and the Group Member Attribute Keys aren't being added to the group either.

We have set up a defined type with 2 values as the primary partition, and group role type as the second partition. After setting up the numbers for the roles, when people sign up the available positions never decreases.

The value from the Group Member Attribute never goes to the group either.

Initially this worked but it stopped after a day. I then removed everything and started form scratch and I still get the same results, neither works. Are there any known issues or trouble shooting steps to take?

Edit: Tested this on a fresh install 8.5 and got the same results.

**Comment by cbump** [comment]
A new version of the Signup Wizard plugin was released this weekend which, hopefully, will address your issues with the counts as well as a major issue mapping attributes from the signup wizard through to the actual connection/group which, I believe, was actually the major cause of your issue.  Please let me know if your issue persists after you upgrade to the latest version.

Thanks!

Chuck Bump
Southeast Christian Church
