### ISSUE TITLE
SignUp Wizard: How to allow users to select multiple schedules

### ISSUE THREAD

**Issue by nathanp** [secc/RockPlugins#69]
I have successfully set up the plugin using 2 partitions (_Role_ and _Schedule_).
Currently, users can only select one schedule. How can I allow them to select multiple schedules as seen in the demo video? (https://rock.secc.org/Content/RockBlog/Plugins/SignupWizard/21CardWizardVideo.mp4)

Thanks for this great plugin!

**Comment by cbump** [comment]
Hi @nathanp this is a very old question at this point but you should be able to update the CardWizardMode to multiple in the Lava tab in the block settings to achieve the result you are looking for:
![image](https://user-images.githubusercontent.com/1248118/96669350-0a2a5500-132b-11eb-9558-eaef691d8b01.png)
