### ISSUE TITLE
Pastoral Care plugin

### ISSUE THREAD

**Issue by azmichaelm** [secc/RockPlugins#7]
We loaded the plugin however when we click on the Dashboard Hospitalization LIst we get a Configuration Error Block not configured. Please configure to use. When we click the link for the hospital list there is definitely something missing in the block configuration. Any thoughts?

![hospital block error](https://user-images.githubusercontent.com/43424131/45784344-3095d780-bc1d-11e8-8f21-8d4c56bd6222.png)
![hospital error](https://user-images.githubusercontent.com/43424131/45784345-3095d780-bc1d-11e8-9cd3-79a7e2a9bc5c.png)

**Comment by azmichaelm** [comment]
Well I went to click on dashboard and now this is what I get... can't go forward...

![dashboard](https://user-images.githubusercontent.com/43424131/45849677-c4cc7100-bce7-11e8-9d07-1d0b1522ace5.png)

**Comment by cbump** [comment]
Do you still need/want help with this?  This seems like a separate issue but I just want to make sure you get all the help you need.

**Comment by azmichaelm** [comment]
Yes, we still need to figure out how to get into the Dashboard as that is where we list our hospitals etc… I’m thinking it was a setting that might have gotten set while trying to make it work. I’d uninstall the plugin and reinstall however we have no idea how to accomplish that.
