### ISSUE TITLE
Signup Wizard: Schedule Sorting not working

### ISSUE THREAD

**Issue by nathanp** [secc/RockPlugins#75]
We are using v1.3 of the Signup Wizard plugin.
When using the SignUp wizard with a Schedule partition, the sorting is not sorting by either schedule date OR schedule ID (I created the schedules sequentially, in order).

The dates are being shown as follows:
1. Jan. 1
2. Jan. 10
3. Jan. 11
...
4. Jan. 19
5. Jan. 2
6. Jan. 20

At first, I tried adding a zero to the beginning of the single-digit dates (Jan. 01, Jan. 02, etc.) but they were still in the above order.

Would appreciate any help with this.
Thanks!

**Comment by scottharland** [comment]
Running into the same issue here on a new signup (picture attached). Similarly to OP, schedule dates were created sequentially and although the order shows correctly on the schedules list, the November dates show in the wrong order on the signup (tried all 3 signup display types and it's in the wrong order on each). Even reversing the names/dates of these two schedules to make the ScheduleId non-sequential, once the name and date match (11/8) the order on the sign-up page displays incorrectly; surprisingly, if the schedule is _named_ 11/8 but the schedule _date_ is 11/22, and vice versa, the order is correct on the signup page.
<img width="865" alt="Screen Shot 2020-09-01 at 10 38 17 AM" src="https://user-images.githubusercontent.com/11403970/91887241-60d6b500-ec3f-11ea-89e0-ca4d84bde1e2.png">

**Comment by scottharland** [comment]
We successfully used [this hotfix](https://github.com/secc/RockPlugins/commit/f2c32298658433486c4550455f1de62bd10fa79f) to correct the sorting issue until the plug-in update is published to the Rock Shop.

**Comment by cbump** [comment]
Hi @nathanp this issue should be resolved in the latest version of the plugin which is available in the Rock shop now.  Thanks for working together to patch it temporarily until we were able to find time to get the plugin updated.  We appreciate your patience!
