### ISSUE TITLE
v11 Upgrade Issue

### ISSUE THREAD

**Issue by chrissusskin** [secc/RockPlugins#87]
Receiving this message when looking at volunteer block: ERROR: C:\inetpub\wwwroot\Plugins\org_secc\Connection\VolunteerSignupWizard.ascx.cs(958): error CS0619: 'Schedule.NextStartDateTime' is obsolete: 'Use GetNextStartDateTime( DateTime currentDateTime ) instead.'

**Comment by jcamarin** [comment]
Michael Roth helped me with this exact issue on Chat... here was his solution that fixed this for me:

On this file: C:\inetpub\wwwroot\Plugins\org_secc\Connection\VolunteerSignupWizard.ascx.cs

Line 958 needs to be 
partition.PartitionValue = String.Join( ",", scheduleService.GetByIds( scheduleIds ).ToList().OrderBy( s => s.GetNextStartDateTime( RockDateTime.Now ) ).Select( s => s.Guid.ToString() ) );

Line 1092 needs to be:
values = scheduleService.GetByGuids( values.AsGuidList() ).ToList().OrderBy( s => s.GetNextStartDateTime( RockDateTime.Now ) ).Select( s => s.Guid.ToString() ).ToArray();

The change was from s.NextStartDateTime to s.GetNextStartDateTime( RockDateTime.Now ) in 2 places in the file.

**Comment by cbump** [comment]
Hey @chrissusskin, thank you for reporting this.  This should be resolved in the latest version of the plugin which is now available in the Rock shop.  Thanks!
