### ISSUE TITLE
Error Loading Block

### ISSUE THREAD

**Issue by jcamarin** [secc/RockPlugins#88]
I am getting this error message when trying to use the Volunteer Signup Wizard Block. 

<img width="1162" alt="Screen Shot 2020-09-29 at 12 48 52 PM" src="https://user-images.githubusercontent.com/44300741/94596993-9678b900-0252-11eb-8559-fc061072c1af.png">

**Comment by jcamarin** [comment]
Michael Roth helped me with this exact issue on Chat... here was his solution that fixed this for me:

On this file: C:\inetpub\wwwroot\Plugins\org_secc\Connection\VolunteerSignupWizard.ascx.cs

Line 958 needs to be 
partition.PartitionValue = String.Join( ",", scheduleService.GetByIds( scheduleIds ).ToList().OrderBy( s => s.GetNextStartDateTime( RockDateTime.Now ) ).Select( s => s.Guid.ToString() ) );

Line 1092 needs to be:
values = scheduleService.GetByGuids( values.AsGuidList() ).ToList().OrderBy( s => s.GetNextStartDateTime( RockDateTime.Now ) ).Select( s => s.Guid.ToString() ).ToArray();

The change was from s.NextStartDateTime to s.GetNextStartDateTime( RockDateTime.Now ) in 2 places in the file.

**Comment by TheArkChurch** [comment]
I'm also had the same error.

**Comment by jcamarin** [comment]
If you give me your email address I can send you the two .ascx.cs files that need replaced on your webserver. These changes worked for me It worked for me. Or you can copy the code changes from above for one of the files.
